'use strict';

/**
 * Lightweight OpenAPI/Swagger documentation generator.
 * Serves a /api-docs JSON endpoint and optionally a Swagger UI HTML page.
 */
function createSwaggerMiddleware(config) {
  if (!config.swagger) return null;

  const swaggerConfig = typeof config.swagger === 'object' ? config.swagger : {};
  const path = swaggerConfig.path || '/api-docs';
  const title = swaggerConfig.title || 'Express Starter API';
  const version = swaggerConfig.version || '1.0.0';
  const description = swaggerConfig.description || 'API documentation generated by express-starter-kit';

  const spec = {
    openapi: '3.0.3',
    info: { title, version, description },
    servers: [{ url: `http://localhost:${config.port || 3000}` }],
    paths: {},
    components: {
      schemas: {},
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
    },
  };

  function addRoute(method, routePath, options = {}) {
    const cleanPath = routePath.replace(/\/:([^/]+)/g, '/{$1}');
    if (!spec.paths[cleanPath]) spec.paths[cleanPath] = {};
    spec.paths[cleanPath][method.toLowerCase()] = {
      summary: options.summary || `${method.toUpperCase()} ${routePath}`,
      tags: options.tags || ['default'],
      parameters: options.parameters || [],
      requestBody: options.requestBody,
      responses: options.responses || {
        200: { description: 'Success' },
        400: { description: 'Bad Request' },
        500: { description: 'Internal Server Error' },
      },
      security: options.security,
    };
  }

  function getSpec() {
    return spec;
  }

  function middleware(req, res, next) {
    if (req.path === path && req.method === 'GET') {
      const accept = req.headers.accept || '';
      if (accept.includes('text/html')) {
        res.setHeader('Content-Type', 'text/html; charset=utf-8');
        res.send(generateSwaggerUI(path));
      } else {
        res.json(spec);
      }
      return;
    }
    next();
  }

  return { middleware, addRoute, getSpec };
}

function generateSwaggerUI(specUrl) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>API Documentation</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({ url: '${specUrl}', dom_id: '#swagger-ui' });
  </script>
</body>
</html>`;
}

module.exports = { createSwaggerMiddleware };
