'use strict';

const fs = require('fs');
const path = require('path');

const TEMPLATES = {
  basic: {
    description: 'Basic Express server with health checks',
    dependencies: { express: '^4.18.2' },
  },
  auth: {
    description: 'Express server with JWT authentication and User model',
    dependencies: { express: '^4.18.2', bcrypt: '^5.1.0', jsonwebtoken: '^9.0.0' },
  },
  websocket: {
    description: 'Express server with Socket.io WebSocket support',
    dependencies: { express: '^4.18.2', 'socket.io': '^4.7.0' },
  },
  full: {
    description: 'Full-featured Express server with auth, WebSocket, Redis, and more',
    dependencies: {
      express: '^4.18.2',
      bcrypt: '^5.1.0',
      jsonwebtoken: '^9.0.0',
      'socket.io': '^4.7.0',
      redis: '^4.6.0',
    },
  },
};

function generateProject(projectName, options) {
  const targetDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(targetDir)) {
    if (!options.force) {
      throw new Error(`Directory ${projectName} already exists. Use --force to overwrite.`);
    }
    fs.rmSync(targetDir, { recursive: true, force: true });
  }

  const template = TEMPLATES[options.template] || TEMPLATES.basic;
  const dbDialect = options.db || 'postgres';
  const useRedis = options.redis || false;

  const dirs = ['models', 'routes', 'controllers', 'middleware', 'config', 'logs'];
  dirs.forEach((d) => fs.mkdirSync(path.join(targetDir, d), { recursive: true }));

  // package.json
  const pkg = {
    name: projectName,
    version: '1.0.0',
    description: `Express application generated by express-starter-kit (${options.template} template)`,
    main: 'index.js',
    scripts: {
      dev: 'nodemon src/index.js',
      start: 'node src/index.js',
      test: 'jest --coverage',
      lint: 'eslint . --ext .js',
      format: 'prettier --write "**/*.{js,json,md}"',
    },
    dependencies: {
      'express-starter-kit': '^1.0.0',
      ...template.dependencies,
    },
    devDependencies: {
      nodemon: '^3.0.0',
      jest: '^29.7.0',
      eslint: '^8.50.0',
      prettier: '^3.0.0',
    },
  };

  if (dbDialect === 'sqlite') {
    pkg.dependencies.sqlite3 = '^5.1.0';
  } else if (dbDialect === 'mysql') {
    pkg.dependencies.mysql2 = '^3.6.0';
  } else {
    pkg.dependencies.pg = '^8.11.0';
    pkg.dependencies['pg-hstore'] = '^2.3.4';
  }

  if (useRedis) {
    pkg.dependencies.redis = '^4.6.0';
  }

  fs.writeFileSync(path.join(targetDir, 'package.json'), JSON.stringify(pkg, null, 2));

  // .env.example
  const envContent = `# Server
PORT=3000
NODE_ENV=development

# Database
DATABASE_URL=${dbDialect === 'sqlite' ? 'sqlite://./data.db' : `${dbDialect}://user:password@localhost:5432/${projectName}`}

# Session
SESSION_SECRET=change-me-to-a-random-string

${useRedis ? '# Redis\nREDIS_URL=redis://localhost:6379\n' : ''}# Logging
LOG_LEVEL=debug
`;
  fs.writeFileSync(path.join(targetDir, '.env.example'), envContent);

  // .gitignore
  fs.writeFileSync(path.join(targetDir, '.gitignore'), `node_modules/
.env
*.log
coverage/
dist/
`);

  // src/index.js
  const srcDir = path.join(targetDir, 'src');
  fs.mkdirSync(srcDir, { recursive: true });

  const srcContent = `const { createApp } = require('express-starter-kit');

async function main() {
  const { app, ready } = await createApp({
    port: process.env.PORT || 3000,
    nodeEnv: process.env.NODE_ENV || 'development',
    database: {
      url: process.env.DATABASE_URL,
      dialect: '${dbDialect}',
      sync: { alter: true },
    },
    ${useRedis ? 'redis: { url: process.env.REDIS_URL, enabled: true },' : ''}
    sessionSecret: process.env.SESSION_SECRET,
  });

  await ready;

  app.listen(process.env.PORT || 3000, () => {
    console.log(\`Server running on port \${process.env.PORT || 3000}\`);
  });
}

main().catch((err) => {
  console.error('Failed to start:', err);
  process.exit(1);
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.js'), srcContent);

  // Example User model
  const modelContent = `const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const User = sequelize.define('User', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: { isEmail: true },
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    timestamps: true,
  });

  User.associate = (models) => {
    // Define associations here
  };

  return User;
};
`;
  fs.writeFileSync(path.join(targetDir, 'models', 'User.js'), modelContent);

  // Example auth route
  if (options.template === 'auth' || options.template === 'full') {
    const authRouteContent = `const { Router } = require('express');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

const router = Router();

router.post('/register', async (req, res) => {
  try {
    const { email, password, name } = req.body;
    const hashed = await bcrypt.hash(password, 10);
    const user = await req.sequelize.models.User.create({ email, password: hashed, name });
    res.status(201).json({ id: user.id, email: user.email, name: user.name });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await req.sequelize.models.User.findOne({ where: { email } });
    if (!user || !(await bcrypt.compare(password, user.password))) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }
    const token = jwt.sign({ id: user.id, email: user.email }, process.env.SESSION_SECRET, { expiresIn: '7d' });
    res.json({ token, user: { id: user.id, email: user.email, name: user.name } });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

module.exports = router;
`;
    fs.writeFileSync(path.join(targetDir, 'routes', 'auth.js'), authRouteContent);
  }

  // Dockerfile
  const dockerfile = `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD ["node", "src/index.js"]
`;
  fs.writeFileSync(path.join(targetDir, 'Dockerfile'), dockerfile);

  // docker-compose.yml
  const composeServices = {
    version: '3.8',
    services: {
      app: {
        build: '.',
        ports: ['3000:3000'],
        environment: {
          NODE_ENV: 'production',
          DATABASE_URL: `${dbDialect}://postgres:postgres@db:5432/${projectName}`,
          SESSION_SECRET: 'change-me',
        },
        depends_on: ['db'],
      },
      db: {
        image: dbDialect === 'mysql' ? 'mysql:8' : 'postgres:15',
        environment: {
          POSTGRES_USER: 'postgres',
          POSTGRES_PASSWORD: 'postgres',
          POSTGRES_DB: projectName,
        },
        volumes: ['db_data:/var/lib/postgresql/data'],
      },
    },
    volumes: { db_data: {} },
  };

  if (useRedis) {
    composeServices.services.redis = {
      image: 'redis:7-alpine',
      ports: ['6379:6379'],
    };
    composeServices.services.app.environment.REDIS_URL = 'redis://redis:6379';
    composeServices.services.app.depends_on.push('redis');
  }

  fs.writeFileSync(path.join(targetDir, 'docker-compose.yml'), JSON.stringify(composeServices, null, 2));

  // README
  const readme = `# ${projectName}

Generated by \`express-starter-kit init\` using the **${options.template}** template.

## Quick Start

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`

## Scripts

- \`npm run dev\` - Start with hot reload
- \`npm start\` - Start production server
- \`npm test\` - Run tests
- \`npm run lint\` - Lint code

## Environment Variables

See \`.env.example\` for all required variables.
`;
  fs.writeFileSync(path.join(targetDir, 'README.md'), readme);

  return targetDir;
}

module.exports = { generateProject, TEMPLATES };
